export const cellToGridIndex = (cell) => {
  const colMap = { b: 0, i: 1, n: 2, g: 3, o: 4 };
  const col = colMap[cell[0]];
  const row = parseInt(cell[1]) - 1;
  return row * 5 + col;
};

export const getBallColor = (number) => {
  if (number >= 1 && number <= 15) return "#ed1b24";
  if (number >= 16 && number <= 30) return "#00adef";
  if (number >= 31 && number <= 45) return "#fba919";
  if (number >= 46 && number <= 60) return "#9f4d9d";
  if (number >= 61 && number <= 75) return "#004a49";
  return "#4b5563";
};

export const formatPatternName = (pattern) => {
  if (pattern === "row") return "ኣንድ ኣግዳሚ መስመር/Any one Horizontal";
  if (pattern === "column") return "ኣንድ የቆመ መስመር/Any one Vertical";
  if (pattern === "diagonal") return "Any Diagonal";
  if (pattern === "oneLine") return "ኣንድ መስመር ብቻ/Any Line";
  if (pattern === "fourCorners") return "ኣራቱ ማኣዝን ነጠብጣብ/Four corner";
  if (pattern === "innerCorners") return "Inner Corners";
  if (pattern === "lPattern") return "L Shape";
  if (pattern === "reverseL") return "Reverse L";
  if (pattern === "tPattern") return "T Shape";
  if (pattern === "reverseT") return "Reverse T";
  if (pattern === "plus") return "Plus";
  if (pattern === "square") return "Square";
  if (pattern === "xPattern") return "ሁለት ዲያጎናል/X pattern (both diagonals)";
  if (pattern === "uPattern") return "U Shape";
  if (pattern === "cross") return "Cross";
  if (pattern === "diamond") return "Diamond";
  if (pattern === "postageStamp") return "Postage Stamp";
  if (pattern === "bigDiamond") return "Big Diamond";
  if (pattern === "letterH") return "Letter H";
  if (pattern === "letterC") return "Letter C";
  if (pattern === "letterE") return "Letter E";
  if (pattern === "letterF") return "Letter F";
  if (pattern === "letterI") return "Letter I";
  if (pattern === "letterN") return "Letter N";
  if (pattern === "letterP") return "Letter P";
  if (pattern === "letterS") return "Letter S";
  if (pattern === "letterY") return "Letter Y";
  if (pattern === "letterZ") return "Letter Z";
  if (pattern === "checkmark") return "Checkmark";
  if (pattern === "heart") return "Heart";
  if (pattern === "arrow") return "Arrow";
  if (pattern === "anyLineOrCorner") return "ኣንድ መስመር /Any Line or Corner";
  if (pattern === "anyLinePlusCorner") return "Any Line Plus Corner";
  if (pattern === "anyTwoLinesOrCorners") return "Any Two Lines or Corners";
  if (pattern === "anyCornerSquare") return "Any Corner Square";
  if (pattern === "smallPlus") return "Small Plus";
  if (pattern === "kite") return "Kite";
  if (pattern === "pyramid") return "Pyramid";
  if (pattern === "clover") return "Clover";
  if (pattern === "sixPack") return "Six Pack";
  if (pattern === "insideSquare") return "Inside Square";
  if (pattern === "perimeter") return "Perimeter";
  if (pattern === "letterA") return "Letter A";
  if (pattern === "letterD") return "Letter D";
  if (pattern === "letterK") return "Letter K";
  if (pattern === "letterL") return "Letter L";
  if (pattern === "letterM") return "Letter M";
  if (pattern === "letterO") return "Letter O";
  if (pattern === "letterR") return "Letter R";
  if (pattern === "letterU") return "Letter U";
  if (pattern === "letterV") return "Letter V";
  if (pattern === "letterW") return "Letter W";
  if (pattern === "number7") return "Number 7";
  if (pattern === "doubleX") return "Double X";
  if (pattern === "threeCorners") return "Three Corners";
  if (pattern === "adjacentCorners") return "Adjacent Corners";
  if (pattern === "star") return "Star";
  if (pattern === "circle") return "Circle";
  if (pattern === "railroadTracks") return "Railroad Tracks";
  if (pattern === "frame") return "Frame";
  if (pattern === "butterfly") return "Butterfly";
  if (pattern === "LXYZ") return "LXYZ";
  if (pattern === "anyL") return "Any L";
  if (pattern === "anyT") return "Any T";
  if (pattern === "Tplus") return "T Plus";
  if (pattern === "TplusReverse") return "T Plus Reverse";
  if (pattern === "spider") return "Spider";
  if (pattern === "smileyFace") return "Smiley Face";
  if (pattern === "triangle") return "Triangle";
  if (pattern === "zigzag") return "Zigzag";
  if (pattern === "crescent") return "Crescent";
  if (pattern === "lightningBolt") return "Lightning Bolt";
  if (pattern === "anyTwoLine") return "ሁለት መስመር/Any Two Lines";
  if (pattern === "anyTwoHorizontalLine") return "ሁለት ኣግዳሚ መስመር/Any two Horizontal";
  if (pattern === "anyTwoVerticalLine") return "ሁለት የቆመ መስመር/Any two Vertical";
  if (pattern === "anyThreeLine") return "Any 3 Lines";
  if (pattern === "allSingleMiddleCorner")
    return "All Single or Middle Corners";
  if (pattern === "innerOrfourCorners") return "Inner or outer Four Corners";
  if (pattern === "anyFourLine") return "Any 4 Lines";
  if (pattern === "anyFiveLine") return "Any 5 Lines";
  if (pattern === "anySixLine") return "Any 6 Lines";
  if (pattern === "anySevenLine") return "Any 7 Lines";
  if (pattern === "fullCard") return "Full House/ሙሉ ዝግ";
  if (pattern === "badBingo") return "Bad Bingo";
  return pattern.charAt(0).toUpperCase() + pattern.slice(1);
};
